name: CI CD Common Pipeline

on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string
      apptype:
        required: true
        type: string
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        if: ${{ inputs.apptype == 'java' }}
        run: mvn clean package
      - name: Upload artifact
        if: ${{ inputs.apptype == 'java' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.component }}-jar
          path: target/${{ inputs.component }}-1.0.jar
          retention-days: 1

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo npm test ## We will not have echo command in real world. Since this is a test application there are not test cases built.

  docker:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Docker login
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 739561048503.dkr.ecr.us-east-1.amazonaws.com
      - name: Download artifact
        if: ${{ inputs.apptype == 'java' }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.component }}-jar
          path: ./
      - run: docker build -t 739561048503.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.component }} .
        name: Docker Build
      - run: docker push 739561048503.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.component }}
        name: Docker push

  dev-deploy:
    needs: docker
    runs-on: self-hosted
    environment: dev
    steps:
      - uses: actions/checkout@v4
        with:
          repository: raghudevopsb87/roboshop-helm-v1
      - name: Get kubectl config
        run: aws eks update-kubeconfig --name dev
      - name: argocd login
        run: |
          argocd_password=$(kubectl get secrets argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 --decode)
          argocd login https://argocd-dev.rdevopsb87.online/ --insecure --username admin --password $argocd_password
      - name: Create App in ArgoCD
        run: argocd app create ${{ inputs.component }} --repo https://github.com/raghudevopsb87/roboshop-helm-v1.git --path . --dest-namespace default --dest-server https://kubernetes.default.svc --values dev-project-values/${{ inputs.component }}.yml
      - name: Sync App in ArgoCD
        run: argocd app sync ${{ inputs.component }}
      - name: ArgoCD App health Check 
        run: argocd app wait ${{ inputs.component }} --timeout 60

  qa-deploy:
    needs: dev-deploy
    runs-on: self-hosted
    environment: qa
    steps:
      - uses: actions/checkout@v4
        with:
          repository: raghudevopsb87/roboshop-helm-v1
      - name: Get kubectl config
        run: aws eks update-kubeconfig --name dev
      - name: argocd login
        run: |
          url=$(kubectl get svc argocd-server  -o jsonpath='{.status.loadBalancer.ingress[*].hostname}')
          argocd_password=$(kubectl get secrets argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 --decode)
          argocd login $url --insecure --username admin --password $argocd_password
      - name: Create App in ArgoCD
        run: argocd app create ${{ inputs.component }} --repo https://github.com/raghudevopsb87/roboshop-helm-v1.git --path . --dest-namespace default --dest-server https://kubernetes.default.svc --values qa-project-values/${{ inputs.component }}.yml
      - name: Sync App in ArgoCD
        run: argocd app sync ${{ inputs.component }}
      - name: ArgoCD App health Check
        run: argocd app wait ${{ inputs.component }} --timeout 60

  uat-deploy:
    needs: qa-deploy
    runs-on: self-hosted
    environment: uat
    steps:
      - uses: actions/checkout@v4
        with:
          repository: raghudevopsb87/roboshop-helm-v1
      - name: Get kubectl config
        run: aws eks update-kubeconfig --name dev
      - name: argocd login
        run: |
          url=$(kubectl get svc argocd-server  -o jsonpath='{.status.loadBalancer.ingress[*].hostname}')
          argocd_password=$(kubectl get secrets argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 --decode)
          argocd login $url --insecure --username admin --password $argocd_password
      - name: Create App in ArgoCD
        run: argocd app create ${{ inputs.component }} --repo https://github.com/raghudevopsb87/roboshop-helm-v1.git --path . --dest-namespace default --dest-server https://kubernetes.default.svc --values uat-project-values/${{ inputs.component }}.yml
      - name: Sync App in ArgoCD
        run: argocd app sync ${{ inputs.component }}
      - name: ArgoCD App health Check
        run: argocd app wait ${{ inputs.component }} --timeout 60

  prod-deploy:
    needs: uat-deploy
    runs-on: self-hosted
    environment: prod
    steps:
      - uses: actions/checkout@v4
        with:
          repository: raghudevopsb87/roboshop-helm-v1
      - name: Get kubectl config
        run: aws eks update-kubeconfig --name dev
      - name: argocd login
        run: |
          url=$(kubectl get svc argocd-server  -o jsonpath='{.status.loadBalancer.ingress[*].hostname}')
          argocd_password=$(kubectl get secrets argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 --decode)
          argocd login $url --insecure --username admin --password $argocd_password
      - name: Create App in ArgoCD
        run: argocd app create ${{ inputs.component }} --repo https://github.com/raghudevopsb87/roboshop-helm-v1.git --path . --dest-namespace default --dest-server https://kubernetes.default.svc --values prod-project-values/${{ inputs.component }}.yml
      - name: Sync App in ArgoCD
        run: argocd app sync ${{ inputs.component }}
      - name: ArgoCD App health Check
        run: argocd app wait ${{ inputs.component }} --timeout 60